# Generated by Django 3.2.5 on 2021-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='result',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cal',
            name='value_a',
            field=models.FloatField(max_length=20),
        ),
    ]
