# Generated by Django 3.2.5 on 2021-07-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0002_auto_20210708_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='value_a',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cal',
            name='value_b',
            field=models.IntegerField(max_length=20),
        ),
    ]
